# PGTP Editor — companion editor for SQL Maestro PostgreSQL PHP Generator .pgtp files
# Copyright (C) 2026  Botond Zalai-Ruzsics
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

from importlib import resources
from pathlib import Path

from PySide6.QtCore import QStandardPaths

_MODEL_FILENAME = "schema_model.json"
_CURATED_XSD_FILENAME = "curated.xsd"
_LEARNED_XSD_FILENAME = "learned.xsd"

# The curated schema bundled with the app (spec §11). On first run, when the
# user's app-data curated.xsd is absent, it is seeded by copying this resource.
CURATED_BUNDLED_VERSION = "1.2"
_BUNDLED_CURATED_RESOURCE = "curated.xsd"


def _app_data_dir() -> Path:
    return Path(QStandardPaths.writableLocation(QStandardPaths.StandardLocation.AppDataLocation))


def schema_model_path(base_dir: Path | None = None) -> Path:
    return (base_dir or _app_data_dir()) / _MODEL_FILENAME


def curated_xsd_path(base_dir: Path | None = None) -> Path:
    """The official, hand-curated schema (spec §11). Hand-edited only —
    never machine-written except the one-time bootstrap."""
    return (base_dir or _app_data_dir()) / _CURATED_XSD_FILENAME


def learned_xsd_path(base_dir: Path | None = None) -> Path:
    """The generated discovery artifact regenerated by auto-learning.
    Never feeds completion; never touches curated.xsd."""
    return (base_dir or _app_data_dir()) / _LEARNED_XSD_FILENAME


def bundled_curated_xsd_text() -> str | None:
    """Text of the curated schema shipped with the app (Curated
    v{CURATED_BUNDLED_VERSION}), or None if the resource is not packaged.
    Used to seed the user's curated.xsd on first run (spec §11)."""
    try:
        resource = resources.files("pgtp_editor") / "resources" / _BUNDLED_CURATED_RESOURCE
        return resource.read_text(encoding="utf-8")
    except (FileNotFoundError, ModuleNotFoundError, OSError):
        return None
